services:
  crypto-svovnenko:
    build:
      context: .
      dockerfile: dockerfile.debug
      args:
        SERVER_PORT: 8080
    environment:
      SPRING_PROFILES_ACTIVE: ${VAR_PROFILE:-ci}
      JDK_JAVA_OPTIONS: -ea -server -Dserver.port=8080
    ports:
      - "8080:8080"